### PR TITLE
Minor revisions to variables

### PR DESCRIPTION
**Pull request by idlebear**
Set up auto build of conan files if not present
Corrected test for variable(s)

### CODE REVIEW

**Comment by ltjax** [comment]
Hello there, thanks for contributing!
Can you elaborate on your `if()` changes? It looks like the variables are now dereferenced twice, which feels wrong to me (although it probably still works) - did it not work for you before? Or did I miss something?
I'm not especially keen on running conan from within cmake. I am also against the "flakyness" of using `find_file()`. E.g., right now the `find_file` will succeed if it finds a` conanbuildinfo.cmake` in your defaults. I do like the better error message though. It looks to be more comfortable like this, but also more brittle.

**Comment by idlebear** [comment]
No worries at all.

The if() changes are necessary to test the value of the variable -- add this line to the CMakeLists.txt to see what I mean:
```
message( ${PROJECT_NAME}_USE_CONAN " is " ${${PROJECT_NAME}_USE_CONAN} )
```
Without it, the test was always true.  (I was trying to build without conan tests, but cmake kept complaining..)

For find_paths(), maybe add NO_DEFAULT_PATH so it doesn't search anywhere other than the suggested location:
```
find_file( Conan_BUILD_INFO conanbuildinfo.cmake ${CMAKE_CURRENT_BINARY_DIR} NO_DEFAULT_PATH )
```

I'm not a cmake wizard by any means, but hope this makes sense.

**Comment by ltjax** [comment]
Well, I guess there's some confusion on the if()s then. No wonder, cmake is very confusing there. But it does automatically evaluate variables - without the `${}`. See the "Variable Expansion" Section here: https://cmake.org/cmake/help/latest/command/if.html - `message()`, OTOH, does not do that.
I just double checked that I can disable conan and tests with these parameters on the command-line: `-Ddecomp_USE_CONAN=OFF -Ddecomp_BUILD_TESTS=OFF`

Well, in that case, we could also just use `if(EXISTS ${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)` and bump out, if it's not there, no?

**Comment by idlebear** [comment]
Like I said, not a cmake genius -- I think I was trying to get cmake to rebuild its cache at the time and may have confused the two isses. And yes, since finding the path, just checking for existence is probably more than sufficient.  Feel free to close this one.

**Pull request closed without merging**
